spring:
#  cloud:
#    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        server-addr: localhost:8848
#        namespace: public
#        group: dev
#  profiles:
#    active: dev
  datasource:
    db1:
      url: jdbc:postgresql:///db1
      username: postgres
      password: 123.com
    db2:
      url: jdbc:postgresql:///db2
      username: postgres
      password: 123.com
  application:
    name: people-service
#    db3:
#      url: jdbc:postgresql:///db3
#      username: postgres
#      password: 123.com
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  .
  mapper-locations: classpath:mappers/*.xml
#  config-location: classpath:mappers/*.xml
server:
  port: ${port:80}

