spring:
#  cloud:
#    nacos:
#      discovery:
#        username: nacos
#        password: nacos
#        server-addr: localhost:8848
#        namespace: public
  datasource:
    dynamic:
      # 主数据库
      primary: db1
      # 严格匹配数据源，默认为false，true：未匹配指定数据源抛异常，false：使用默认数据库
      strict: false
      datasource:
        db1:
          url: jdbc:postgresql:///db1
          username: postgres
          password: 123.com
          driver-class-name: org.postgresql.Driver
        db2:
          url: jdbc:postgresql:///db2
          username: postgres
          password: 123.com
          driver-class-name: org.postgresql.Driver


#    db3:
#      url: jdbc:postgresql:///db3
#      username: postgres
#      password: 123.com
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
server:
  port: ${port:80}

